### ISSUE TITLE
gradlew BUILD failed

### ISSUE THREAD

**Issue by Ingo60** [Frege/FregeFX#1]
When I do

```
./gradlew run
```

the build fails with

```
Downloading https://services.gradle.org/distributions/gradle-2.6-bin.zip
 ...... (many more dots)
Unzipping /home/ingo/.gradle/wrapper/dists/gradle-2.6-bin/7og9jkn1p1nxjafu1htp0hhvc/gradle-2.6-bin.zip to /home/ingo/.gradle/wrapper/dists/gradle-2.6-bin/7og9jkn1p1nxjafu1htp0hhvc
Set executable permissions for: /home/ingo/.gradle/wrapper/dists/gradle-2.6-bin/7og9jkn1p1nxjafu1htp0hhvc/gradle-2.6/bin/gradle
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-gradle-plugin/0.4.2-SNAPSHOT/frege-gradle-plugin-0.4.2-20150822.225452-7.pom
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-native-gen/1.3/frege-native-gen-1.3.pom
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-repl-core/1.2/frege-repl-core-1.2.pom
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-interpreter-core/1.0.5/frege-interpreter-core-1.0.5.pom
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-repl-nativedeps/1.2/frege-repl-nativedeps-1.2.pom
Download https://oss.sonatype.org/content/groups/public/jline/jline/2.12/jline-2.12.pom
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-interpreter-java-support/1.0.5/frege-interpreter-java-support-1.0.5.pom
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-interpreter-core/1.1/frege-interpreter-core-1.1.pom
Download https://oss.sonatype.org/content/groups/public/org/frege-lang/frege-interpreter-java-support/1.1/frege-interpreter-java-support-1.1.pom

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'fregefx'.
> Could not resolve all dependencies for configuration ':classpath'.
> Could not find org.eclipse.jdt.core.compiler:ecj:4.2.2.
 Searched in the following locations:
     file:/home/ingo/.m2/repository/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.pom
     file:/home/ingo/.m2/repository/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.jar
     https://oss.sonatype.org/content/groups/public/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.pom
     https://oss.sonatype.org/content/groups/public/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.jar
     https://jitpack.io/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.pom
     https://jitpack.io/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.jar
 Required by:
     org.frege-lang:fregefx:0.2.0-SNAPSHOT > org.frege-lang:frege-gradle-plugin:0.4.2-SNAPSHOT > org.frege-lang:frege-repl-core:1.2 > org.frege-lang:frege-interpreter-core:1.1 > org.frege-lang:frege-interpreter-java-support:1.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 35.126 secs
```

The irony is that I have this ecj thing probalby in 20 different places on my machine, but this is the weak point of all Java build tools I've ssen so far - there is apparently no way to tell USE THIS ONE, PLEASE

**Comment by Dierk** [comment]
thanks for the notice. 
ECJ comes as a transitive dependency from repl-core. Note sure what is going on there. 
I have some trouble reconstructing the issue (needless to say "it works on my machine" :-))

**Comment by Ingo60** [comment]
Btw, why does the fregefx need the repl at all?

**Comment by Dierk** [comment]
it was the native-gen, which I used in the build, but it should not be required for using fregefx. 

please pull and try again.

**Comment by Ingo60** [comment]
I could build the frege-repl, which also uses this ecc4.2.2, but somehow it is not retained in my cache?

Any tips on this? What do I need to do to let those damned buiilders at least KEEP what they download? Do they think everyone on the planet has UNLIMITED free internet access?

**Comment by Ingo60** [comment]
On a releated note, will it always download 40MB gradle? On every run?

**Comment by Dierk** [comment]
the gradle wrapper installs itself once and subsequent usages need no further download. 
Can it be that the .gradle and .m2 caching subdirs under your user home have trouble writing files?

**Comment by Ingo60** [comment]
No, I guess it is because the frege-repl, which I installed in the hope that it would keep the ecc4.2.2, uses gradel 2.5, while you use 2.6. Apparently, only a single gradle installation is admitted.

Your changes didn't help, it still wants the ecc4.2.2:

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'fregefx'.
  > Could not resolve all dependencies for configuration ':classpath'.
  > Could not find org.eclipse.jdt.core.compiler:ecj:4.2.2.
   Searched in the following locations:
       file:/home/ingo/.m2/repository/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.pom
       file:/home/ingo/.m2/repository/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.jar
       https://oss.sonatype.org/content/groups/public/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.pom
       https://oss.sonatype.org/content/groups/public/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.jar
       https://jitpack.io/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.pom
       https://jitpack.io/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.jar
   Required by:
       org.frege-lang:fregefx:0.2.0-SNAPSHOT > org.frege-lang:frege-gradle-plugin:0.4.2-SNAPSHOT > org.frege-lang:frege-repl-core:1.2 > org.frege-lang:frege-interpreter-core:1.1 > org.frege-lang:frege-interpreter-java-support:1.1

**Comment by Ingo60** [comment]
I think the ecc is here: https://repo1.maven.org/maven2/org/eclipse/jdt/core/compiler/ecj/4.2.2/ecj-4.2.2.pom

This is where the frege-repldownloaded it.

**Comment by Dierk** [comment]
ok, I think now I have it.

**Comment by Ingo60** [comment]
I give up:

ingo@ibinti:~/Frege/FregeFX$ ./gradlew run
please use a Java Version 8
 or set JAVA_HOME   to a dir that contains the jre/lib/jfxrt.jar
 or set JAVAFX_HOME to a dir that contains the rt/lib/jfxrt.jar

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/ingo/Frege/FregeFX/examples/build.gradle' line: 56
- What went wrong:
  location of jfxrt.jar could not be determined
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.167 secs
ingo@ibinti:~/Frege/FregeFX$ java -version
openjdk version "1.8.0_40-internal"
OpenJDK Runtime Environment (build 1.8.0_40-internal-b09)
OpenJDK Server VM (build 25.40-b13, mixed mode)

**Comment by Dierk** [comment]
this check is no longer in any of the newer versions. 
Are you sure you did pull?
A `gradlew clean` may also help.

**Comment by Ingo60** [comment]
ingo@ibinti:~/Frege/FregeFX$ ./gradlew clean
please use a Java Version 8
 or set JAVA_HOME   to a dir that contains the jre/lib/jfxrt.jar
 or set JAVAFX_HOME to a dir that contains the rt/lib/jfxrt.jar

FAILURE: Build failed with an exception.
- Where:
  Build file '/home/ingo/Frege/FregeFX/examples/build.gradle' line: 56
- What went wrong:
  location of jfxrt.jar could not be determined
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.013 secs
ingo@ibinti:~/Frege/FregeFX$

**Comment by Ingo60** [comment]
You know, I cannot exclude the possibility that openjdk-8 indeed does not contain javafx, but I have no idea how to change this.

**Comment by Ingo60** [comment]
I come to the conclusion that gradle only works with Oracle JDK:

ingo@ibinti:~/Frege/FregeFX$ sudo find / -name jfxrt.jar -print
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jfxrt.jar
/usr/share/java/openjfx/jre/lib/ext/jfxrt.jar
ingo@ibinti:~/Frege/FregeFX$ ./gradlew run
please use a Java Version 8
 or set JAVA_HOME   to a dir that contains the jre/lib/jfxrt.jar
 or set JAVAFX_HOME to a dir that contains the rt/lib/jfxrt.jar

FAILURE: Build failed with an exception.

The possibility that jfxrt.jar is under ext/ is simply not anticipated.
And I guess there will be no option to supress this usperfluous and broken check?

**Comment by Ingo60** [comment]
I have installed openjfx, but now I get:

ingo@ibinti:~/Frege/FregeFX$ export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ingo@ibinti:~/Frege/FregeFX$ ./gradlew run
:fregefx:compileJava
:fregefx:compileFrege
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxProperties.fr:962: `javafx.css.StyleablePropertyFactory` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxProperties.fr:1670: `javafx.util.converter.LocalDateTimeStringConverter` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxProperties.fr:1662: `javafx.util.converter.LocalDateStringConverter` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxProperties.fr:1678: `javafx.util.converter.LocalTimeStringConverter` is not a known java class
fregefx.JavaFxProperties: build failed because of compilation errors.
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:7759: `javafx.css.StyleablePropertyFactory` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:760: `javafx.scene.AccessibleRole` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:674: `javafx.scene.AccessibleAction` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:694: `javafx.scene.AccessibleAttribute` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:1183: `javafx.scene.control.Alert` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:1203: `javafx.scene.control.ButtonBar` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:1233: `javafx.scene.control.ButtonType` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:1624: `javafx.scene.control.ChoiceDialog` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:1857: `javafx.scene.control.DialogEvent` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:1791: `javafx.scene.control.Dialog` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:1872: `javafx.scene.control.DialogPane` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:2617: `javafx.scene.control.SpinnerValueFactory` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:2587: `javafx.scene.control.Spinner` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:3017: `javafx.scene.control.TextFormatter` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:3102: `javafx.scene.control.TextInputDialog` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:8460: `javafx.util.converter.LocalDateTimeStringConverter` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:8452: `javafx.util.converter.LocalDateStringConverter` is not a known java class
E /home/ingo/Frege/FregeFX/fregefx/src/main/frege/fregefx/JavaFxAll.fr:8468: `javafx.util.converter.LocalTimeStringConverter` is not a known java class
fregefx.JavaFxAll: build failed because of compilation errors.
fregefx.JavaFxUtils: build failed because module `fregefx.JavaFxAll` not built.
Build failed.
runtime 28.634 wallclock seconds.
:fregefx:compileFrege FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':fregefx:compileFrege'.
  
  > Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 48.782 secs

It looks like there are classes missing in the openjdk version. What a mess!

**Comment by Dierk** [comment]
this check has nothing to do with gradle per se. 
I did that check myself in the build of the "examples" because the example relies on javafx runtime being there to execute the code (and compiling will most likely also fail with the javafx classes being on the classpath).
I have pushed a version with the check disabled.

**Comment by Ingo60** [comment]
It is one of those days ....
See my previous comment, there are obvioulsy different vesirons of JavFX floating around.
The funny thing is I am quite sure I have used Java7 to run the FxRepl before.

**Comment by Dierk** [comment]
This can well be. The old version had only a few classes natively declared - obviously ones that are available in javafx 2.2 (that comes with java 7) and javafx 8. The new fregefx version has declarations for all classes in javafx 8.

**Comment by Dierk** [comment]
does the download work for you? The compiled version may work...
https://dl.dropboxusercontent.com/u/71750979/Frege/frepl-0.6.0.zip

**Comment by Ingo60** [comment]
Is the example the repl actually?
You could have told me! Then I wouldn't need to build it myself.
I thought there were another example/demo included.

**Comment by Dierk** [comment]
There is another example - a very small one that contains only a button that one can press :-)
https://github.com/Frege/FregeFX/blob/master/examples/src/main/frege/fregefx/example/HelloWorld.fr
![bildschirmfoto 2015-08-24 um 22 36 47](https://cloud.githubusercontent.com/assets/51843/9451736/aafdb31c-4ab0-11e5-9611-bad6ed43121e.png)
