### ISSUE TITLE
Missing data types

### ISSUE THREAD

**Issue by mchav** [Frege/FregeFX#11]
I'm trying to use a grid pane but I noticed that it is commented out in the code. Any particular reason why?

**Comment by Dierk** [comment]
It is an intermediate state.
You can just remove the comment and use it.
Ingo was working on a change to the native declarations where that specific one would no longer be needed (which would be great). But the change is not yet there.

**Comment by mchav** [comment]
Alright. That makes sense. When will the process be done? Anything I can contribute towards?

**Comment by Dierk** [comment]
we have to check with @Ingo60. Original planning was to be finished by end of year but it looks like we need a bit more time. 
Any help is greatly appreciated and the native decls look like a very good issue to start with.

**Comment by mchav** [comment]
What exactly about native declarations? Any chance we can move this to a private chat of sorts?

**Comment by Dierk** [comment]
sure, we can proceed on gitter, where these kind of discussions usually take place:
https://gitter.im/Frege/frege

**Comment by Ingo60** [comment]
At this time, I simply can't tell when the feature mentioned by @Dierk  will work, or if it will turn out to be possible at all. It's all just very much in my head, still.
